### ISSUE TITLE
All shortcut keys are not working.

### ISSUE THREAD

**Issue by ytabuchi** [Grabacr07/SylphyHorn#35]
Tried workaround: 

- Just Re-install app.
- Uninstall app and reboot os then re-install app.
- change check and uncheck sometimes to some settings such as `Override OS default key`.

PC/OS/App environment: 

- Surface Pro 4
    - Core -5-6300U @ 2.40GHz
    - 8GB
- Windows 10 Pro 64bit
    - 1709
    - 16299.547
- SyophyHorn
    - version 3.0.0

App log: 

It occours when app has launched. 

```
System.InvalidCastException: 指定されたキャストは有効ではありません。
   場所 WindowsDesktop.Interop.ComInterfaceWrapperBase.Invoke[T](Object[] parameters, String methodName)
   場所 WindowsDesktop.Interop.ApplicationViewCollection.GetViewForHwnd(IntPtr hWnd)
   場所 WindowsDesktop.VirtualDesktop.PinWindow(IntPtr hWnd)
   場所 SylphyHorn.UI.SettingsWindow.OnContentRendered(EventArgs e)
   場所 System.Windows.Window.<PostContentRendered>b__198_0(Object unused)
   場所 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   場所 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

ご確認、よろしくお願いいたします。その他ログが取れる場所があれば提出しますので、お知らせください。

**Comment by R-OLE** [comment]
Same symptoms as OP. Attempts same workarounds. Same results.
Also tried changing hotkeys away from default and back again, with zero effect.
Tried booting with anti-virus suite disabled - no change.

I had left message on Issue #32. Here is some feedback on supposed resolution from there:
- Automatic update to v3.1.0 did NOT resolve this issue for me.
- Don't see any mention of v3.1.0 on [https://github.com/Grabacr07/SylphyHorn/], so have no idea what that update was meant to address.

Environment:
- Dell i7 workstation
- Win10 Build 16299 64b
- current with hotfixes
- using SylphyHorn v3.1.0


App log contains the following 3 entries, with entries repeated couple times after each startup, in various order:

System.InvalidCastException: Specified cast is not valid.
   at WindowsDesktop.Interop.ComInterfaceWrapperBase.Invoke[T](Object[] parameters, String methodName)
   at WindowsDesktop.Interop.ApplicationViewCollection.GetViewForHwnd(IntPtr hWnd)
   at WindowsDesktop.VirtualDesktopHelper.MoveToDesktop(IntPtr hWnd, VirtualDesktop virtualDesktop)
   at SylphyHorn.Services.VirtualDesktopService.MoveToLeft(IntPtr hWnd)
   at SylphyHorn.ApplicationPreparation.<>c.<RegisterActions>b__14_3(IntPtr hWnd)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
----------------------------------------------------------------------------------
System.InvalidCastException: Specified cast is not valid.
   at WindowsDesktop.Interop.ComInterfaceWrapperBase.Invoke[T](Object[] parameters, String methodName)
   at WindowsDesktop.Interop.ApplicationViewCollection.GetViewForHwnd(IntPtr hWnd)
   at WindowsDesktop.VirtualDesktop.PinWindow(IntPtr hWnd)
   at SylphyHorn.UI.SettingsWindow.OnContentRendered(EventArgs e)
   at System.Windows.Window.<PostContentRendered>b__198_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
----------------------------------------------------------------------------------
System.InvalidCastException: Specified cast is not valid.
   at WindowsDesktop.Interop.ComInterfaceWrapperBase.Invoke[T](Object[] parameters, String methodName)
   at WindowsDesktop.Interop.ApplicationViewCollection.GetViewForHwnd(IntPtr hWnd)
   at WindowsDesktop.VirtualDesktopHelper.MoveToDesktop(IntPtr hWnd, VirtualDesktop virtualDesktop)
   at SylphyHorn.Services.VirtualDesktopService.MoveToRight(IntPtr hWnd)
   at SylphyHorn.ApplicationPreparation.<>c.<RegisterActions>b__14_7(IntPtr hWnd)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
----------------------------------------------------------------------------------

I'll keep checking if/when an updated version is posted, or pushed to MS store.

**Comment by makeneko** [comment]
- same error happend.
- app log is same with @ytabuchi
- notification has no problem

PC/OS/App environment:
    Surface Laptop
        Core -5-7300U @ 2.60GHz
        8GB
    Windows 10 Pro 64bit
        1709
        16299.547
    SyophyHorn
        version 3.1.0

**Comment by ParticleMon** [comment]
Same issue but no error.

W10 Home x64, 1803, 17134.471
SylphyHorn 3.1.0

**Comment by ytabuchi** [comment]
I have replaced Windows OS and some environment. So right now, I can use it without errors. 

But I have no idea how to fix it...

**Comment by R-OLE** [comment]
- Still running the same Sylphyhorn v3.1.0 (did not uninstall, just have not been running it),
- Last week I updated Win10 to release 1809, after installing the monthly hotfixes,
- And now Sylphyhorn v3.1.0 seems to be working just fine (**YAY!**)
- But note an older open source version of an app similar to this one, that I had been using very well under build 16299, STOPPED working.

Would be **really** nice if Microsoft would try to stabilize this API, or at _least_ document any and all changes for sake of folks making its features easy and useful to use!
